# name: 'Terraform'

# on:
#   pull_request: 
#     branches: [ "main" ]
#     types: closed
#   workflow_dispatch:
  
# permissions:
#   contents: read
#   id-token: 'write'

# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     environment: production

#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
#     defaults:
#       run:
#         shell: bash

#     steps:
#     # Checkout the repository to the GitHub Actions runner
#     - name: Checkout
#       uses: actions/checkout@v4

#     # Install the latest version of Terraform CLI
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v3
    
#     #
#     - name: Authenticate to Google Cloud 
#       uses: 'google-github-actions/auth@v3'
#       with:
#         service_account: ${{ vars.SERVICE_ACCOUNT_ID }}
#         workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_ID }}
#         create_credentials_file: true
#         export_environment_variables: true

#     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#     - name: Terraform Init
#       run: terraform -chdir=domain init

#     # Checks that all Terraform configuration files adhere to a canonical format
#     #- name: Terraform Format
#     #  run: terraform -chdir=environment/dev fmt -check

#     # Generates an execution plan for Terraform
#     - name: Terraform Plan
#       run: terraform -chdir=domain plan -input=false

#     # On push to "main", build or change infrastructure according to Terraform configuration files
#     - name: Terraform Apply
#       if: >
#         (github.event_name == 'pull_request' &&
#         github.event.action == 'closed' &&
#         github.event.pull_request.merged == true &&
#         github.event.pull_request.base.ref == 'main') ||
#         github.event_name == 'workflow_dispatch'
#       run: terraform -chdir=domain apply -auto-approve -input=false